= HID Auxiliary  Library for Arduino =

This library allows an Arduino board with USB capabilities and connected LCD display to act as 
a HID-compliant Auxiliary Display to the host computer, which can be used for displaying any system output
such as CPU/GPU temperature, fan speed, used memory or any other information.  


For more information about USB HID specs please read https://www.usb.org/sites/default/files/hut1_22.pdf

== Supported Arduinos ==
* Leonardo
* (Pro)Micro

== Setup & Usage ==
TBD

== Additional setup step on Linux hosts ==
TBD

== Tested on Operating Systems ==
TBD

== License ==

Copyright (c) Alex Bratchik 2021. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
